### ISSUE TITLE
Support to Sandbox module to use FeaturePopups on OL Drupal

### ISSUE THREAD

**Issue by jorix** [jorix/OL-FeaturePopups#10]
The references:
- The [sandbox of the Drupal Experimental Project](http://drupal.org/sandbox/Pol/1877914) branch: "7.x-2.x"
- The [Drupal OL issue](http://drupal.org/node/1369012)

**Comment by jorix** [comment]
Hi @Polzme 

**Deploying the FP**:

I have not established a criterion to mark stable versions, with tags I guess so.

Now I believe that the control is in a stable point.

I find it curious that the entire code of OL2.12 is added, probably there are many components that are not used (e.g. formats or some controls as TransformFeature ...)

> ... and maybe I'll need a help hand from you if you're ok.

Yes, of course.

> All I really hope is that FP gets included in OL

Sure, I'd like to, but I think it is difficult. I suggested to DEV list in September but no one answered the proposal.

**The sandbox code**:

I've looked at the code and pointed some feedback, if they are useful to you... ok, otherwise ignore them.
- About `$form['layers'][$id]['mode'] = array(...` The options are not mutually exclusive, could assign more than one e.g. `DEFAULT = SAFE_SELECTION | CLOSE_ON_UNSELECT | CLOSE_BOX | UNSELECT_ON_CLOSE`
- There is something wrong, you create a control for each layer but then only adds to the map the last control that was created. Note that one FP allows to show one popup with the list of selected features in each of the layers (grouped by layers)
- About `boxSelectionOptions: {},`, you really want to use the selection box? (by `KeyMask: OpenLayers.Handler.MOD_CTRL`)
- I have to emphasize that the FP have different defaults that the SelectFeature, the differences for `selectOptions` are: `clickout: false, multipleKey: 'shiftKey', toggleKey: 'shiftKey'`
- As defined templates can be all string. Especially recommended try use: 

```
Drupal.theme.prototype.openlayersPopupItem = function() {
  return '<li><a href="#" ${showPopup()}>${.name}</a></li>';
};
```
- The control also allows use i18n for literals, so `'<b>${count} features:</b><br>${html}'` could be `'<b>${count} ${i18n("features")}:</b><br>${html}'`

maybe is too much? ;-)

**Comment by jorix** [comment]
more...

I've seen the normal module only creates a single SelectFeature for all layers, this would also be preferable using FP.

I saw that in the first versions you doing this way, some of my comments made ​​you change option?

**Comment by drupol** [comment]
Hello @jorix,

Huge thanks for your advices, I'll implement them today after work, I was busy the past days.

It's cool that you created a new thread ! Thanks again !

**Comment by drupol** [comment]
All the changes has been implemented :) http://drupalcode.org/sandbox/Pol/1877914.git/tree/refs/heads/7.x-2.x

**Comment by jorix** [comment]
@Polzme See the suggested changes on a clone of the sandbox:
- Don't use mode on each layer and templates only as string with possible improvements.: https://github.com/jorix/sandbox-1877914/commit/ccfd6b0ed088bd525039bbe60b1fae3a4099f121
- Forced down a specific version v1.0.xx: https://github.com/jorix/sandbox-1877914/commit/ccfd6b0ed088bd525039bbe60b1fae3a4099f121 so we know it's tried everything in this version and the main branch can evolve.

They are just notes to talk about it if you think fit.

**Comment by jorix** [comment]
...and in the first commit must remove more lines (at the end), but you will know better how.

**Comment by drupol** [comment]
Excellent, I made the changes.

Everything is working as it should :)

BTW, why removing the 'mode' setting ? Maybe it can be usefull to someone ?

**Comment by jorix** [comment]
Oops! is `${i18n("features")}`, sorry. 

Just is a possible option. The control uses OL literals. Each translate text to be added to code this way:

```
OpenLayers.Util.extend(OpenLayers.Lang.en, {
    'features': "features",
    ...
});
OpenLayers.Util.extend(OpenLayers.Lang.xx, {
    'features': "xxxxxxx",
    ...
});
...
```

**Comment by drupol** [comment]
I already fixed it :)

I don't think this will be useful as Drupal already has it's own translation system, but let's add it in the template, it might be useful to someone maybe.

Also, I'm writing the README.txt to release a module with your extension and in the same time, I'm making a mechanism in the module and bundle it with the version v1.0.0, so it will be easier for the newcomers.

I think it's time for you to create an account on drupal.org :) héhéhé :)

**Comment by jorix** [comment]
> I don't think this will be useful as Drupal already has it's own translation system, but let's add it in the template, it might be useful to someone maybe.

Drupal literals are accessible using js? Anyway currently control only makes the translation when added the layer. 
(In Catalonia is a bilingual land and to have translated literals is important)

> ...with the version v1.0.0, so it will be easier for the newcomers.

Ok, If any other bug, I could move forward the version. We will not be strict if we are coordinated.

> I think it's time for you to create an account on drupal.org :) héhéhé :)

Is a temptation, really. But it's so great...

---

And more details:
- about: `patches_OL-popup-autosize.js` its use is optional, only some mismatch fixes of automatic sizing of OL popups.
-  jsdoc `@param feature` could be removed, no parameter.

**Comment by jorix** [comment]
And a question: In OL Drupal module all OL features have only two attributes ("name" & "description") If not we can talk about this.

**Comment by drupol** [comment]
Do you know if we can use the options PanIfOutOfView and keepInMap ? ([See this in OpenLayers default popup behavior](http://drupalcode.org/project/openlayers.git/blob/refs/heads/7.x-2.x:/plugins/behaviors/openlayers_behavior_popup.js#l76))

I'll do the small changes before releasing, someone came at home, I lost some time.

For the attributes, we can add more attributes through Drupal, it's not a problem.

**Comment by drupol** [comment]
Just released as an official module: http://drupal.org/project/olfp

Congratulations :)

Let's improve it and fix the problem in the [current popup implementation](http://drupalcode.org/project/openlayers.git/blob/refs/heads/7.x-2.x:/plugins/behaviors/openlayers_behavior_popup.js) now !

**Comment by jorix** [comment]
> Just released as an official module: http://drupal.org/project/olfp

For an addict like me, this is really exciting ;-)

Thanks @Polzme 

---

> Do you know if we can use the options PanIfOutOfView and keepInMap ?

Yes by default `panMapIfOutOfView: true` can try:

```
var fpControl = new OpenLayers.Control.FeaturePopups({
   popupSingleOptions: {panMapIfOutOfView: xxx},
   popupListOptions: {panMapIfOutOfView: xxx},
   popupListItemOptions: {panMapIfOutOfView: xxx}
});
```

but by default:

```
   popupHoverOptions: {panMapIfOutOfView: false},
   popupHoverListOptions: {panMapIfOutOfView: false}
```

and is not recommended to change this for hover popups.

Note that the control also makes an internal management and is not always appropriate to move the map when the active popup is refreshed.

Also note that in the case of a line or polygon not used this `feature.geometry.getBounds().getCenterLonLat()` is preferred the mouse position.

And `keepInMap: true` by default, can be changed by creating a class of popup... see at http://www.trafficguide.ro/harta.js makes heavy use of FP customizability.

here would make sense to speak of `mode`, and ... Enough for now ;-)

> For the attributes, we can add more attributes through Drupal, it's not a problem.

So the layer description could be something like: template-title and template-description with default values "${.name}" and "${.description}" ??

---

+Google has realized and showed me your profile.

**Is not true that**: _+Xavier Mamano is about to make a pull request to include this in the main OL module._ 

I do not think the OL team is receptive to such proposals. I would like it very much. But I think not may be accepted by them :-(

The team's concern is not the ease of use or the UI, and see who has more patches pending application: https://github.com/openlayers/openlayers/pulls

I have no problems on other people to do the proposal, but I will not do it, nor is it an invitation to make it you. I just wanted to clarify my position.

**Comment by drupol** [comment]
Sorry Xavier, I will correct on Google+ right now.

**Comment by drupol** [comment]
Thanks for the explanations on panMapIfOutOfView and keepInMap :)

About the layer description, what do you mean ? I don't get you on that one :(

**Comment by jorix** [comment]
> About the layer description, what do you mean ? I don't get you on that one :(

Thinking about this:

In "openlayers_behavior_fp.inc" add two fields for each layer: "templateTitle" and "templateDescription".
And in "openlayers_behavior_fp.js" define a thing as:

```
// for each theme:
Drupal.theme.prototype.openlayersPopupSingle = function(title, description) {
    title = title || '${.name}';
    description = description || '${.description}';
    return 
       '<div class="openlayers-fp openlayers-tooltip-name">' + title + '</div>' +
       '<div class="openlayers-fp openlayers-tooltip-description">' + description + '</div>';
};
...

// and for each layer:

templates.single = Drupal.theme(
    'openlayersPopupSingle', layeroptions.templateTitle, layeroptions.templateDescription);
...

```

In this way attributes of OL features can be free. 

But I do not know if it is too complicated in the environment of the OL Drupal.

Another type of theme is to add functions to calculate the length or area or ..., it can be placed in the `featureContext` when 

```
fpControl.addLayer(layer, {
      templates: templates
      featureContext: {
          area: function(feature) { ... },
          ...
      }
    })
```

and teplate may be: " .... ${area} ..."

Just so you know the possibilities that may be of interest.

**Comment by drupol** [comment]
Working on this today :)

**Comment by drupol** [comment]
Just committed some changes to include the template customisation,... I tried it, it's fantastic :)

Documentation inside the module is on it's way !

**Comment by jorix** [comment]
> Just committed some changes to include the template customisation,...

I have looked at the changes in the code and I noticed that my suggestions will have been useful, perfect!
You have chosen to use the templates individually and give more flexibility to the user, **Good!**
But if you use this way **should take into account** that exists another template `list` with the default value `'<h2>${layer.name} - ${count}</h2><ul>${html}</ul>'` (see docs of [addLayer](http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/api/files/lib/FeaturePopups-1-js.html#OpenLayers.Control.FeaturePopups.addLayer))

_...reading your code..._

This may be a typo into `openlayers_behavior_fp.js`:

```
    layeroptions = layeroptions || '';
    layeroptions.templates = layeroptions.templates || '';
\\ instead of
    layeroptions = layeroptions || {};
    layeroptions.templates = layeroptions.templates || {};

```

and: 
`templates.item = Drupal.theme('olfpitem', layeroptions.templates.item);` into `if (tooltip) {`

> Documentation inside the module is on it's way !

The control also has documentation compiled on pages for consultation [api](http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/api) and [all](http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/all). But my English is not enough for a user who is not benevolent.

---

**Here I must again mention the subject of `fid`**

The control currently used by default as identifiers of the features this function:

```
function(feature) {
  return feature.fid || feature.id;
}
```

(customizable for each layer)

This allows memorizing the features that temporarily destroy some strategies as `BBOX` or `Refresh`. And is also the basis on which work with the `Cluster`.

**The potential problem**: _If the identifier exists, it must be unique for all of features from the layer_.

With **Bogdandragomir** we have seen that their CMS of http://www.trafficguide.ro generated feature pairs with the same identifier, and this was correct.

Then we must use:

```
function(feature) {
  return feature.id;
}
```

which is perfect for `Cluster` but has no utility for `BBOX` and `Refresh`

...and the question is: **Is there this problem using Drupal?**

ok, this is what I wanted to mention!

**Comment by drupol** [comment]
Hello Xavier,

I've implemented the list template too.
I've also made some fixes based on your suggestions.

Drupal generates a different id for each feature, so I suppose that this is not important for now.

---

I'll submit the module to some people for further tests and I'll release the first stable release.
BTW, do you plan to create a new release to fix #11 ?

Thanks again :)

**Comment by jorix** [comment]
> I've implemented the list template too.

ok, the assignment `templates.list = Drupal.theme('olfplist'` could go inside of `if (popup) {`

> Drupal generates a different id...

ok

> BTW, do you plan to create a new release to fix #11 ?

Did not mention it explicitly, I moved forward v1.0.0, the #11 is inside. 
(not very elegant, it really is my first version to release. Now we are in release candidate phase)

If you do not that's okay I can leave the thing as before and create a new version at the end of the publishing process of FP-OL-Drupal.

**Comment by jorix** [comment]
Hi @Polzme 

Some time ago there is no movement here. If there is no objection I'll close this issue.

But first there is one detail that you should consider:

in your `openlayers_behavior_fp.js` the assignment 

```
templates.list = Drupal.theme('olfplist' ...
```

should go inside the:

```
if (popup) {
```

otherwise when `popup` is false the popups appear if 'olfplist' has value.

**Comment by drupol** [comment]
Thanks Xavier, I fixed it :-)
