### ISSUE TITLE
Enable Tooltip without Popup ?

### ISSUE THREAD

**Issue by drupol** [jorix/OL-FeaturePopups#11]
Hello,

Is it possible to enable the tooltips without enabling the popup feature (onclick) ?

Thanks.

**Comment by jorix** [comment]
@Polzme  Is a bug. You did it correctly, try now 266113812ca0591134aa5786786cf7ea5a94387c

**Comment by drupol** [comment]
Dude, you rocks... it works perfectly now :) Thanks !
