### ISSUE TITLE
Is it possible to specify the max form size (height) and add a vertical scroll bar ? 

### ISSUE THREAD

**Issue by jorix** [jorix/OL-FeaturePopups#12]
When I click a cluster (select) and there's a long list of features it doesn't fit the popup form.
For example a list of 35 features doesn't fit and creates a 'new form' at the bottom of the main popup form.
Is it possible to specify the max form size (height) and add a vertical scroll bar ? 

Open in the thread [Disperse Overlapping points/markers after loading](http://osgeo-org.1560.n6.nabble.com/Disperse-Overlapping-points-markers-after-loading-kml-file-vector-layer-td5038242.html) of list DEV list

**Comment by jorix** [comment]
> Is it possible to specify the max form size (height) 

yes could use eg:

```
new OpenLayers.Control.FeaturePopups({
    popupListOptions: {maxSize: new OpenLayers.Size(null, 300)},
    ...
})
```

to control the size of the list popups. See [API docs](http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/api) for more options.

>  add a vertical scroll bar ?

the scroll bar should appear, is not the case?

**Comment by ghost** [comment]
Works excellent. Thanks you very much.

**Comment by jorix** [comment]
@robertico01 

It is gratifying to see this is useful. Thank you also for the feeback :-)

I close this issue.

Open new issues if you have any questions, issues are welcome.
