### ISSUE TITLE
Replace string value

### ISSUE THREAD

**Issue by ghost** [jorix/OL-FeaturePopups#14]
I use this for my popup;

**hover: ${.description},**

How can i replace a part of **"${.description}"** ?
I've already tried a lot but no luck so far.

More specific the description contains the path to a thumbnail. 
I'd like to replace the relative path **<img src=".....** for the full path **<img src=" /uploads/.....**

The easiest way for me is using a fuction and check if it's a relative path or already a full path.
I'm completely stuck.

**Comment by jorix** [comment]
Hi @robertico01 

Could use a function as a template: 

```
hover: function(feature) {
    var myCustomDescription = featue.attributes.description;
    .... your code ...
    return myCustomDescription;
},
```

see also js code of [feature-popups.html](http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html) that uses a function as a template.

Or use context that allows sharing a function on various templates:

```
templates: {
  hover: '${myTitle}',
  single: '<h1>${myTitle}</h1>${myDescription}',
  ... other templates ... 
},
featureContext: {
  myTitle: function(feature) {
    ... your code ...
  },
  myDescription: function(feature) {
    ... your code ...
  },
  ... more ..
}
```

I do not know if the documentation is able to explain these concepts, see in [API of addLayer](http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/api/files/lib/FeaturePopups-1-js.html#OpenLayers.Control.FeaturePopups.addLayer)

**Comment by ghost** [comment]
Thanks a million...

Also tried this for **${showPopup()}**
But is seems empty while the hover popup works fine now.

**Comment by jorix** [comment]
> Also tried this for ${showPopup()} ...

is intended only for use in 'item' template:

```
item: '...<a href="#" ${showPopup()}>...</a>...'
```

its meaning may seem a bit concealed use. 

Serves to activate a link in a list popup to show the single popup of feture of the item. See main example.

**Comment by ghost** [comment]
> is intended only for use in 'item' template:

I should be clearer. It's used in the 'item' template.

But I also tried to use **${showPopup()}** in a function like 'description' 

`item: function(feature) {
    var myCustomPopupMsg = ${showPopup()};
   .... my code ...
   return myCustomPopupMsg ;
},`

But it's not working this way.

**Comment by jorix** [comment]
`${showPopup()}` can not be used in function templates, use a template of text and functions declared in `featureContext`, see above.

**Comment by ghost** [comment]
Thanks. I'll give it a try.

I've changed it;

`layerListTemplate: 'Select an image below<ol>${html}</ol>',
layers: [[
    kml_layer , {
    templates: {
        hover: '${myDescription}',
        single:"<h3>${myName}</h3>${myDescription}",                        
        item: "<center><li><a href=\"#\" ${myDescription}>${.name}</a></li></center>",
    },
    featureContext: {
          myName: function(feature) {
            var myCustomName = feature.attributes.name;
            return myCustomName;
          },
          myDescription: function(feature) {
            var oldPath = feature.attributes.description;
            var newPath = oldPath.replace("<img src=\"","<img src=\"/uploads/0001/");
            return newPath;
          },
        },
    }
]]`

But the popup after selecting a cluster isn't a nice list. It shows all the 'description' items as hyperlinks.
I need the same list as using **${showPopup()}** that show's a nice list of items (hyperlink by name) 
The only thing i need to change is the relative path for the thumbnails.

Is this caused by;
`layerListTemplate: 'Select an image below<ol>${html}</ol>',`

It might be a stupid question, but I'm not able to solve it.

**Comment by jorix** [comment]
Try:

```
layerListTemplate: 'Select an image below<ol>${html}</ol>',
layers: [[
    kml_layer , {
            templates: {
                hover: '${myDescription}',
                single:"<h3>${.name}</h3>${myDescription}", 
                 // <center> must be into <li>
                item: "<li><center><a href=\"#\" ${showPopup()}>${.name}</a></center></li>"
                // comma removed, a trailing comma causes IE fails               
            },
            featureContext: {
                myDescription: function(feature) {
                    var oldPath = feature.attributes.description;
                    var newPath = oldPath.replace("<img src=\"","<img src=\"/uploads/0001/");
                    return newPath;
                }// comma removed, a trailing comma causes IE fails
        }// comma removed, a trailing comma causes IE fails
    }
]]
```

Note that your `myDescription` function alters only the first image on `attributes.description`

> ... but I'm not able to solve it.

...do not worry, we all have our first time ;-)

**Comment by ghost** [comment]
It works excellent. Thank you very much.
Also usefull comments !

> Note that your myDescription function alters only the first image on attributes.description

Do you mean that it only replaces the first occurrence of _<img src=\"_ and that I need a global replacement for multiple occurances?
If so, I'm aware of that. Otherwise please clarify.

**Comment by jorix** [comment]
> > alters only the first image
> 
> ... I need a global replacement for multiple occurances?
> If so, I'm aware of that. ...

just a comment, I do not know what your application needs.

**Comment by ghost** [comment]
There's just one image. So it fit my needs and I've learned something today ;-)

**Comment by ghost** [comment]
Is it also possible to replace the icon path retrieved from the KML file ?
( Is there a specific attribute for the icon (e.g. feature.attributes.icon) )

I'd like to use the icon specified in the KML file, instead of my own icon.
Only using my own icon when it's not specified in the KML file.

I've tried to find some documentation about the available attributes. No luck.

**Comment by jorix** [comment]
Look it up in `feature.style.externalGraphic`.

But if you want to change the style after changed must do `vectorialLayer.drawFeature(feature);` So it is better to change the style on `"beforefeatureadded"` layer event. Warning using Cluster I think `"beforefeatureadded"` will occur twice. Could be a difficult terrain, not tested.

It is not related with this control.

**Comment by ghost** [comment]
Thank you but his is not what I was looking for.

> It is not related with this control.

Agree and apologies.

**Comment by jorix** [comment]
@robertico01 

> but his is not what I was looking for ... and apologies.

Sorry, I understood that you wanted to change the style of the feature icon. 

What are you looking for?...

oops!... maybe you want to put the icon of the feature in the item of the list popup...
You've tried get `feature.style.externalGraphic`?

**Comment by ghost** [comment]
It's out of the scoop of this topic, but I'll try to explain it a little bit more ;-)

I've several kml files (generated by third party applications)
Sometimes the _IconStyle_ is defined (and sometimes not) in the kml file.
If there's no _IconStyle_ defined ('marker icons'), my own style is used (using _externalGraphic_) - Works fine combined with the cluster strategy !
If there is an _IconStyle_ defined the path for the icon in the kml file is a relative path, e.g _/icon/marker.png_

On my map server I need a full path, e.g _/uploads/00001/icon/marker.png_

It's the same issue as previously described for the thumbnails.
So I wondered if it was possible to replace the _Icon_ path from the kml file as done for the thumbnails.

I hope it is understandable

**Comment by jorix** [comment]
I understand! 

Make your custom KML format, see at [KML.js#L483](https://github.com/openlayers/openlayers/blob/master/lib/OpenLayers/Format/KML.js#L483) (not tested)

I think this is what will cause fewer headaches ;-)

**Comment by ghost** [comment]
Thank you.
Can you recommend me a book or other source to find more of this.
the _JavaScript Mapping Library_  is hard to understand for me and sometimes miss good examples.

**Comment by jorix** [comment]
I learned from [examples of OL](http://openlayers.org/dev/examples/), the [OL wiki](http://trac.osgeo.org/openlayers/wiki) and [API docs](http://dev.openlayers.org/releases/OpenLayers-2.12/doc/apidocs), olso http://docs.openlayers.org/, and also looking at the source code. It may not be a good way.

Sorry, I can not specify other documentation that I have used.

**Comment by ghost** [comment]
Thanks. It's a good starting point for me.
