### ISSUE TITLE
Configure options by layers instead of globally.

### ISSUE THREAD

**Issue by drupol** [jorix/OL-FeaturePopups#15]
Hello Xavier,

I have updated the module to work with the upcoming version of OpenLayers.
I also integrated some options to configure the popupClass; some users would like to display popup outside the map viewport.

While I was doing it, I wondered if it's possible to configure those options per layers instead of globally.

Let me know if it's possible or not and I'll implement it in my module :-)

Thanks !

**Comment by jorix** [comment]
No, this is not possible in the current version. The control seeks to unify the behavior of popups.

There is only one handler for each type of popup (5 types), and all this work coordinated. this is difficult to change it without breaking everything, but...

...if what we want is that the layer is displayed in a external-div or not, I would think is possible add a `externalDiv` as additional option on `options` of `addLayer` method. It is not easy, so I want to know if **this is enough**.

One problem is that when using multiselect in different layers, all the features are displayed in a single popup grouped in layers. (Try it and see what I mean) What to do in this case if two layers indicate the same `externalDiv`?

**Comment by jorix** [comment]
> ...if what we want is that the layer is displayed in a external-div or not, I would think is possible add a externalDiv as additional option on options of addLayer method.

@Polzme: this is enough? 

(unfortunately I do not see any other possibilities, even this alone is a little tricky)

Regards.

**Comment by drupol** [comment]
Hi Xavier,

Thanks for the explanation, it's good.
Of course, adding a externalDiv per layer could be a solution, but it can raise problem indeed.

I don't know what is the best here...

**Comment by jorix** [comment]
This is done: provided by the new option `pupupOptions` in method addLayers.

Usage example on: http://jorix.github.io/OL-FeaturePopups/examples/feature-popups-mixed.html

**Comment by jorix** [comment]
This Improvement is done by [v1.1.0](https://github.com/jorix/OL-FeaturePopups/tree/v1.1.0)
