### ISSUE TITLE
Feature blink/flash

### ISSUE THREAD

**Issue by RemyLespagnol** [jorix/OL-FeaturePopups#16]
Hello Jorix !

I use your library for make popups on my features.

But I have a problem. Without your library, if I put my mouse over the features (markers with images) I have no problems.
But if I use your library, if I put my mouse over my features, these blink/flash...

To use your library on my features i do that : 

```
select = new OpenLayers.Control.FeaturePopups({
          selectionBox: true,
          layers: [[
          vector2 , {templates: { 
hover: "${.name}",
               single:"\<p style=\"color : red;\">description : ${.address}\</p>",
               item: "\<li>\<a href=\"#\" ${showPopup()}>${.name}\</a>\</li>"
           }}
           ]]
       });
map.addControl(select);
select.activate(); 
```

Have you go an idea to fix that ? 
Have you got more informations about this problems ?

Thanks a lot ;)

**Comment by jorix** [comment]
Hi @Themandunord 

I need more information. The `hover` was producing flicker, now moves with the mouse to avoid them. I tried your templates but is no flicker.

Can be a matter of styleMap, when the mouse is over the feature is shown as selected. You use a clause _"select"_ in your styleMap? (tell me which)

It happens with different browsers?

Try don't use hover, so:

```
select = new OpenLayers.Control.FeaturePopups({
    hoverOptions: null,
    ...
});
```

It also flashes?

NOTE: Tomorrow I do not think I can spend time on this :(

**Comment by RemyLespagnol** [comment]
Thanks a lot for your answer !

If I put hoverOptions : null, flickers don't appear !

But I haven't the name if I put my mouse over the marker :/

Thanks ;) And good job !

**Comment by jorix** [comment]
> If I put hoverOptions : null, flickers don't appear !

Ok, then `hover` is the place to investigate.

> But I haven't the name if I put my mouse over the marker :/

Sure! this is not the solution, just to focus the problem to reproduce it.

You use a clause "select" in your styleMap? 

Tell me the styleMap code.

**Comment by RemyLespagnol** [comment]
No, I don't use the clause "select"

This is my styleMap :

```
var style = new OpenLayers.Rule({
            symbolizer: {
                externalGraphic: "${ref}",
                graphicWidth : 21,
                graphicHeight : 25,
                graphicOpacity : 1,
                graphicZIndex : 9999,
                title : "defaultTitle"
            }
        }); 
```

Sorry, I don't know how use the balise for my code...

The popups work, so it is fine for the moment.
If you have go no idea, no problem ;)

**Comment by jorix** [comment]
I'll try when I have some time, this weekend I have so complicated.

I can try it without `title`

> Sorry, I don't know how use the balise for my code...

Use ``` on a line to start and end.

**Comment by RemyLespagnol** [comment]
No problem jorix !

This mouse over is'nt a big problem for my project. Without that is good too.
`hoverOptions : null` help me soo much !

Thanks a lot for your job ;)

**Comment by jorix** [comment]
I could not reproduce the blink/flash. What browser do you use?

In any case, `title` is in conflict with `hover` template, so two tooltips is confusing.

> No problem jorix !

I worked to eliminate flicker. I worry a bit that appear again.

Can you tell me if removing the `title` also occurs? ...and removing only `hover` template?
