### ISSUE TITLE
Popup can't be opened a second time

### ISSUE THREAD

**Issue by j-schumann** [jorix/OL-FeaturePopups#18]
After closing a features popup with the closebox it cannot be opened again, only after clicking another feature.

Test:
http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.html
- click sprinter feature or "my ... title" feature > popup opens
- click closebutton > popup disappears
- click same feature again > no popup
- click other feature > new popup opens
- click old feature > old popup shows again

This also does not work on my installation with a vector layer containing features with graphic/backgroundgraphic.
Opening a popup again on a Sundial feature works.

local featurePopups version: 1.1.0
browser: FF24

**Comment by jorix** [comment]
@j-schumann : This is a bug caused by V1.1.0 :(

Please try 3a8f7c00ed8c4f94f7927eac6b1746cad0447640 and tell me if it works now, thanks.

**Comment by j-schumann** [comment]
No, sorry, both issues still exist with this revision, at least in my installation (http://regio.vrok.de using http://regio.vrok.de/scripts/library/OpenLayers/Control/FeaturePopups.js) but I confirm it's fixed in the example (http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.html)

**Comment by j-schumann** [comment]
Ok, browser cache prevented correct test, both issues are fixed with 3a8f7c0
