### ISSUE TITLE
SafeSelection reopens an already closed popup

### ISSUE THREAD

**Issue by j-schumann** [jorix/OL-FeaturePopups#19]
I have a vector layer containing features loaded by a bbox strategy, so the aren't loaded when not on the map.
If I open a popup of such a feature and close it again, then scroll the map so the feature disappears and then scroll it back in the popup opens again.
This should not happen, a popup closed by the closebox or clickout should not be opened again.

local featurePopups version: 1.1.0
browser: FF24

**Comment by jorix** [comment]
see fix on #18

**Comment by j-schumann** [comment]
Confirm fixed with 3a8f7c0, thanks a lot!
