### ISSUE TITLE
Option to open hover on feature center

### ISSUE THREAD

**Issue by j-schumann** [jorix/OL-FeaturePopups#20]
I have not found an option to define wether or not tooltips (on hover) are opened on the cursor position or at the features center. Popups (on click) seem to get opened always at the feature center.

OpenLayers.Control.FeaturePopups_Utils.showListPopup already supports a parameter "useCursorLocation", could this be added to the popupOptions.hover object?

**Comment by jorix** [comment]
@j-schumann 

Show popups on cursor location is used in two cases: 
- in the selection of lines or polygons (ony single selection)
- on hover-popups (**to prevent flicker when the cursor flies above a hover-popup**)

---

Try this trick to don't use cursor location (not supported by the API):

``` javascript
OpenLayers.Control.FeaturePopups_Utils.getLocationFromHandler = function(featureHandler, feature) {
    return feature.geometry.getBounds().getCenterLonLat();
};
```

If for you the result of this trick is satisfactory I can study put an option in the API for each type of popup (I think it's not hard, but until now I thought it was not necessary)

**Comment by j-schumann** [comment]
This works good.
