### ISSUE TITLE
Cross Browser Issues

### ISSUE THREAD

**Issue by j-schumann** [jorix/OL-FeaturePopups#21]
Hello! I tested http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.html, works like a charm on Win7 FF24, android browser and chrome on android. (the mobile browsers open popup instead of tooltip on touch as expected)

Now I implemented your control in my application and got some problems: FF24 works as expected but android browser shows the hover tooltips instead of the single popup and android chrome doesn't show anything.
Can currently be seen under: http://regio.vrok.de

Do you have any idea why this could be? There are no other SelectFeature controls enabled and there are no browser switches implemented from my side.

``` javascript
       map.addControl(new OpenLayers.Control.FeaturePopups({
            layers: [[this.layers[layerName], {templates: {
                hover: function(feature) {
                    return feature.attributes.tooltip;
                },
                single: '<div><h2>${.name}</h2>${.description}</div>'
            }}]],
            popupOptions: {
                hover: {
                    popupClass: OpenLayers.Popup.CustomTooltip,
                    followCursor: false,
                    anchor: {
                        size: new OpenLayers.Size(0,0),
                        offset: new OpenLayers.Pixel(0,0)
                    }
                },
                single: {
                    popupClass: OpenLayers.Popup.CustomPopup
                }
            }
        }));
```

**Comment by jorix** [comment]
@j-schumann 

To separate causes try it without altering the `popupClass`, so

``` javascript
var fpControl = new OpenLayers.Control.FeaturePopups({
    ...
    popupOptions: {
        hover: {
            followCursor: false,
            anchor: null
        },
        hoverList: {
            followCursor: false,
            anchor: null
        }
    },
});   

```

NOTES:
- `anchor: null` gives the same result as `anchor: {size: new OpenLayers.Size(0,0), offset: new OpenLayers.Pixel(0,0)}`
- These parameters can produce flicker when the cursor flies above a hover-popup.

**Comment by j-schumann** [comment]
Thanks for the support. I made the changes you suggested. I prefer to have no anchor preset as this largely depends on the size of the marker graphics used and I rather set the position via CSS.

To the problem: It seems to be caused by the Navigation/TouchNavigation controls, as long as I have one of those activated there are no popups (Chrome) or only the hover popups (android browser). All other controls are deactivated.
I am currently out of ideas why this could be, as it works in your demo with enabled navigation. Maybe it's the creation order?

**Comment by j-schumann** [comment]
It is an order problem: If I create the Navigation control first, and later activate FeaturePopups it works, otherwise not. Is this expected behaviour?

This makes it quite difficult for me as I normally generate the vector layers first, with them create the popup control if popups are enabled and afterwards create all additional controls as some of them may also require a vector layer. I will see how to solve that.

**Comment by jorix** [comment]
> If I create the Navigation control first, and later activate FeaturePopups it works, otherwise not. Is this expected behaviour?

Maybe: 

I see that `OpenLayers.Control.CustomTooltip` is loaded. The `CustomTooltip` is inherited from `SelectFeature`, and if active collide with `FeaturePopups` that also use two internar `SelectFeature`

Can not be activated simultaneously both: `CustomTooltip` + `FeaturePopups`!!!

---

Note not related with FeaturePupups:

I don't use TouchNavigation, I use:

``` javascript
new OpenLayers.Control.Navigation(),
// new OpenLayers.Control.TouchNavigation(),
new OpenLayers.Control.PinchZoom(),
```

For now it looks like a cross-platform solution that works well for maps that I have in production, but now can not remember which were the problem to go to use this.

---

> I prefer to have no anchor preset as this largely depends on the size of the marker graphics used and I rather set the position via CSS.

the anchor only established to locate the hover-popup away from the cursor.

**Comment by j-schumann** [comment]
I used a workaround to create the Navigation control first, then the vector layer and afterwards the click controls, thank you.
