### ISSUE TITLE
Ajax content in popups

### ISSUE THREAD

**Issue by j-schumann** [jorix/OL-FeaturePopups#22]
Is it possible to load the popup content via XHR?
In the callback function I can immediately return content, I need this to create a loading animation and I could start the XHR asynchronously, but still need a handle to the popup to load the HTML into when the XHR is finished. I use a custom popup class that supports the content loading.

Something like this would be great:

``` javascript
                hover: function(feature, popup) {
                    popup.loadContent(feature.popupUrl);
                    return '<img src="loading-anim" />';
                },
```

**Comment by jorix** [comment]
@j-schumann 

Use events to get popup object. 

Try:

``` javascript
var fpControl = new OpenLayers.Control.FeaturePopups({
    popupOptions: {
        hover: {
            eventListeners:{
                popupdisplayed: function(e){
                    console.log(e.object.popup.id);
                }
            }
        }
    },
    ...
});
```

(note that the popup always has the same id but created every time again)

And can asynchronously call `.setContentHTML()` of `e.object.popup` (after checking that has not been destroyed by another process so: `e.object.popup.id !== null`)

**Comment by jorix** [comment]
...and get feature

``` javascript
var fpControl = new OpenLayers.Control.FeaturePopups({
    popupOptions: {
        hover: {
            eventListeners:{
                popupdisplayed: function(e){
                    console.log(e.object.popup.id + ' ' + e.selection.feature.id);
                }
            }
        }
    },
   ...
});
```

**Comment by j-schumann** [comment]
This works as a charm, thanks!
