### ISSUE TITLE
Strange errors with removeLayer

### ISSUE THREAD

**Issue by wisy-uschaefer** [jorix/OL-FeaturePopups#26]
I believe the following could fix the issue, but I'm not sure about what other consequences my fix could have, so I'll post here:

Line 418 is
                var layers = this.layers || [this.layer];
but should be
                var layers = self.layers || [self.layer];

Line 888 is
            delete this.layerObj[layer.id];
but should be
            delete this.layerObjs[layer.id];

**Comment by jorix** [comment]
I agree with your comment about line 888, is a bug, fixed by 45630166b74cf2327757e2d7c84aaaa9c24bba45

---

With respect line 418, I disagree: `this` represents a instance of  `SelectFeature` and `self` represents the instance of `FeaturePopups`. (only `SelectFeature` control have the `layer` property)

Tell me which version of OpenLayers you are using, and how to reproduce your problem and I will look for another explanation of the issue.

**Comment by wisy-uschaefer** [comment]
Hi and thanks for your quick response! I've created a fiddle to demonstrate the issue:
http://jsfiddle.net/7r8qpa0x/1/

The trouble happens if you add a layer, remove it again and hover over its features. I get lots of these: "Uncaught TypeError: Cannot read property 'highlightFeature' of undefined"

I think the problem appears because the layer is removed from the `FeaturePopup`, not from the underlying `SelectFeature`. So the `SelectFeature` requests info on a feature which `FeaturePopup` doesn't know anymore. Replacing `this` with `self` seemed to solve it at first sight.

I'm using OpenLayers 2.13.1.

**Comment by jorix** [comment]
I was able to reproduce the problem. The control does not turn off the listeners correctly.

Now I could not find a good way to solve it. A patch would be:
- change if in line `422`: `if (layerObj !== undefined && layerObj.safeSelection)` & 
- added before line `918`: `if (layerObj === undefined) return;`

but this is not elegant.

During the week is difficult to have the time, I will answer in a few days, most likely in the weekend...

**Comment by jorix** [comment]
Please try now with this patch: d0bb7239330e15a6be005dee32bc927df9e333a4

**Comment by jorix** [comment]
No answer, I guess it worked. Issue closed.
