### ISSUE TITLE
Does FeaturePopups interfere with ModifyFeature?

### ISSUE THREAD

**Issue by jopro** [jorix/OL-FeaturePopups#28]
I have an Issue since I integrated FeaturePopups into my code and I don't know where to look anymore. Maybe it's not because of FeaturePopups anyway. Has this been tried by someone maybe?

Problem is I cannot select a drawn feature by clicking on it anymore. When I don't add the FeaturePopups-Control to the map at start, modifying works again. I looked through the FeaturePopups.js but didn't find anything that could interfere with the ModifyFeature. Both Controls use separate and different Layers.

I'm using a mixture of ExtJS 4 and OL2.13 and I justshow some snippets, hoping it's enough for the first view.

Substantiating the FeaturePopup control:

```
        var fpControl = new OpenLayers.Control.FeaturePopups({
            boxSelectionOptions: {},
            id: 'idGeomaerkerFeatureInfo',
            popupOptions: {'single': {closeBox: true, popupClass: OpenLayers.Popup.Anchored}},
            // mode: 'NONE',
            layers: [
                [
                // Uses: Templates for hover & select and safe selection
                geomaerkerlayer_points, {
                    templates: {
                        // hover: single & list
                        // hover: '${.status}',
                        hover: function(feature){
                            switch(feature.attributes.status) {
                                case "ungeprueft":
                                    return '<table width="370px" style="background-color:#E9F2FF; margin-left:0px; font-family:Verdana, Geneva, Arial, Helvetica, sans-serif; font-size:10pt; border-spacing: 0px;">'

                                     ...

    map.map.addControl(fpControl);

```

Initiating the ModifyControl and some other:

```
        this.drawLayer = new OpenLayers.Layer.Vector('GeomaerkerDraw');
        this.drawLayer.displayInLayerSwitcher = false;
        this.drawLayer.setVisiblitiy = false;

        this.polygonDraw = new OpenLayers.Control.DrawFeature(
                this.drawLayer, OpenLayers.Handler.Polygon);
        this.polygonDraw.handler.stopDown = true;
        this.polygonDraw.handler.stopUp = true;

        this.modify = new OpenLayers.Control.ModifyFeature(this.drawLayer);
        this.modify.mode = OpenLayers.Control.ModifyFeature.RESHAPE;

        this.drawLayer.events.on({"beforefeatureadded": function(){
            if (this.features.length > 0){
                this.removeFeatures(this.features[0]);
            }
        }});

        ...

    /**
     * Activate the tool to modify previously drawn features.
     */
    modifyFeature: function(button) {
        this.deactivate();
        this.deactivateOthers();
        this.modify.activate();
    },

```

I would really appreciate it getting some help here. After all I really like the FeaturePopups and don't want to miss it. Thanks

**Comment by jorix** [comment]
The possible cause is the interaction of the two controls: ModifyFeature & SelectFeature (used internally by FeaturePopups). 
You probably have the same problem using SelectFeature instead of FeaturePopups. 

Try use: [Ragbag/Control/ModifyFeature-tools](https://github.com/jorix/OL-Ragbag/blob/gh-pages/lib/Ragbag/Control/ModifyFeature-tools.js) (Addresses some problems including the multilayer modification and separation of styles editing elements)

**Comment by jorix** [comment]
... and I would not clear that it makes your code:

``` js
   modifyFeature: function(button) {
        this.deactivate(); // What is this.deactivate()?
        this.deactivateOthers(); // What does?
        this.modify.activate();
    },
```

I can not reproduce the problem, you can use a simpler code?

**Comment by jopro** [comment]
Ragbag/Control/ModifyFeature-tools did it for me, thank you very much!

Now I have to figure out how much of your code I really need. We want to exchange OL2 with OL3 in the near future and then I will have to transform your code too.

Do You maybe have some thoughts in transforming to OL3?

Sorry for the incomplete code, but it's a huge bunch and I didn't want to post it all.
I use a ExtJS Toolbar with some completely other controls than drawing and selecting - therefore 
`this.deactivateOthers()` deactivates all those tools on an ExtJS-base.

Inside the currently used tool (selected in the ExtJS Toolbar) the user can draw, modify, remove and save, and `this.deactivate()` deactivates the drawControl and removeControl.

**Comment by jorix** [comment]
> ... exchange OL2 with OL3

I have not worked with OL3 :-(

> Sorry for the incomplete...

No problem, if your code works now :-)
(I did not know if `fpControl.deactivate()` is executed and where, now it does not matter)

**Comment by jopro** [comment]
Thank You!
