### ISSUE TITLE
How to not overlap cluster popups?

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#3]
Hi Jorix!

The control you developed is very useful for me, thank you!
I have used it here http://www.trafficguide.ro/.

I have some questions which I asked for support on http://gis.stackexchange.com, but it looks that too few people is using this control. So I will ask you for support if possible.

I am using cluster popups and there is a small design problem in my opinion: the event popup have the same anchor as the cluster popup and they partial or total overlap.
Is it possible to anchor the second (event) popup on the link on first (cluster) popup?

I think if you give a short answer on the forum (http://gis.stackexchange.com/questions/41483/how-to-not-overlap-cluster-popups-with-featurepopups-control) you will create some more visibility for your control.

Thank you,
Bogdan

**Comment by jorix** [comment]
@bogdandragomir 

I will study the implementation of the opposite anchor in the second popup, so if the list popup is shown top left the second popup will be bottom left.

Aanchor in the link is a job that may be unworkable. I think it is possible to inject the html code of the second popup into the html code of the list popup... I am not convinced... can cause side effects...

Currently you can have two solutions:
- allow second popups will have a close box:

```
var fpControl = new OpenLayers.Control.FeaturePopups({
     popupListItemOptions: {closeBox: true},
     ...
```
- close the list popup when it shows the second popup:

```
var fpControl = new OpenLayers.Control.FeaturePopups({
     popupListItemOptions: {relatedToClear: ['list', 'single']},
     ...
```

NOTE:
I've looked at your code, you use the sentence `... mode: ~OpenLayers.Control.FeaturePopups.CLOSE_BOX, ...`
if you remove modes by subtraction, you must start with the default values​​, as:

```
var fpControl = new OpenLayers.Control.FeaturePopups({
     mode: OpenLayers.Control.FeaturePopups.DEFAULT & 
          ~OpenLayers.Control.FeaturePopups.CLOSE_BOX,
     ...
```

**Comment by bogdandragomir** [comment]
Thank you very much jorix!
The second solution would be ok, but it is not working. The cluster popup is closing after click inside, but the 2nd popup is not showing.
I will use the first solution for the moment. If you find a better solution I would like to test it.

I updated the code as you told me in the note, thanks again.

I see the popups open sometimes in opposite direction (left-right), but not always.

Regards,

**Comment by jorix** [comment]
@bogdandragomir 

> The second solution would be ok, but it is not working.

The first solution has worked for me in all tests yesterday and today.

See the new example: http://jorix.github.com/OL-FeaturePopups/examples/feature-popups-plus.html the first solution works here.

So, if I can not reproduce the bug I can not fix, help me to break it.

**Comment by bogdandragomir** [comment]
It works without problems now, no need to reproduce the old bug.
But there is twice bulets as features on cluster popups.

Thank you Jorix!

**Comment by bogdandragomir** [comment]
On my test server the second popup does not appear after the cluster popup is closed.
Can you imagine a reason for this?
You can see it in action here: http://test2.trafficguide.ro/ 

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

In local I could not reproduce the problem. But debugging http://test2.trafficguide.ro/ I think this may be a solution:
- try use 511ae7ee5088d614ea9aae5f6453144b2c2d6371

Please confirm if it works.

**Comment by bogdandragomir** [comment]
Yes, it works! Thank you!

**Comment by jorix** [comment]
Hi @bogdandragomir after a few days I have to work on it.

Can you test 5a2ebcc6030dc40b09dc30913fe414b16902a9b2 ?

Would you think this behavior acceptable? 
(now by default the two popups are distributed vertically but can be set horizontally by `popupListItemOptions.relatedSimultaneous` option)

**Comment by bogdandragomir** [comment]
I updated the FeaturePopups.js file on http://test2.trafficguide.ro/ but I see no difference on popups open from cluster popups. Please check by clicking on red triangles with a number inside.

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

> ... I see no difference on popups...

Yes, to see this behavior don't use `popupListItemOptions: {relatedToClear: ['list', 'single']},` 
(if the list popup is closed does not make sense)
you can see it in http://jorix.github.com/OL-FeaturePopups/examples/feature-popups.html

**Comment by bogdandragomir** [comment]
You are right, I forgot about this config line.
Now it works ok. Thank you very much!

**Comment by jorix** [comment]
@bogdandragomir ...and thanks for your tests.

I've been thinking about your filter to remove duplicates. In your case it would be interesting to directly display the details of whether the list has only one item: try 74ab72618b86aa47f1dc853b50e3a30ccf92d1f7 + 208decf7d6f142e98b822cf0b2ef7bfed2b4acaa

**Comment by bogdandragomir** [comment]
You are right Jorix. Again :) 
It works fine and your idea is very good. Thank you!

You can see it in action here http://test2.trafficguide.ro/

**Comment by jorix** [comment]
When synchronizing with another popup will force also relative position of marter popup, see 1885257d4a3820c3c91474de3bd4ea6a0f1809eb 

Otherwise, having opened two popups was confusing: so to move the map and zoom the two popups could exchange their relative positions.

**Comment by bogdandragomir** [comment]
I don't understand what you mean by "synchronizing with another popup" and "marter popup".
Can you give me an example?

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

When pressing a list item, the relative positions of the two popups are related, this is what he meant by "synchronizing", and "master" is the list popup.

The problem is _having opened two popups was confusing: so to move the map and zoom the two popups could exchange their relative positions_, so e.g if the item popup is up and the list popup down can happen when you move and zoom that the list is up and item down.

**Comment by bogdandragomir** [comment]
Now I understand. 
So with 1885257 you keep the list popup in the same relative position to the item popup?
Thank you.

**Comment by jorix** [comment]
> ... in the same relative position to the item popup?

Yes, exactly!

So this can be closed.
