### ISSUE TITLE
Layer follows mouse pointer on passing new data

### ISSUE THREAD

**Issue by warlockdn** [jorix/OL-FeaturePopups#30]
I have FeaturePopups used on page load. it plots the data passed from the db to the map and works fine. 

Once data is filtered and new data is passed through json the popup works on hover but it sticks with the mouse pointer and goes wherever the mouse pointer goes.

```
fpControl = new OpenLayers.Control.FeaturePopups({
 layers: [ layer data ]
});

map.addControl(fpControl);
```

**Comment by jorix** [comment]
Please give me more details: 

> Once data is filtered...

how? what js code you use? there exist a url where I could try?

**Comment by warlockdn** [comment]
The thing is its a company product so showing it to you isn't possible since its in our local servers. Anyways I can explain you the process.

There are few ships whose location with lat and lon is with us. Once the page loads we plot all the coordinates into the map and we see the ship as they are in the map with icons and once the cursor is at the icon we see certain details about the ship. It works perfectly. 

Now we have a filtration system through which we can select what ships we want to see. Now it runs the same function and the coordinates are passed through json which plots the filtered ships to the map and it works fine. But when again I take the cursor above the ship I see the hover info about the ship works fine but then the hovered item sticks with the cursor and it will go wherever the cursor goes.

If you get my point. Can you please assist me.

I am using the same format you have used here 

http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.js

![ship](https://cloud.githubusercontent.com/assets/3439710/12999441/29a3d39a-d175-11e5-9b95-10ceb0ccd370.png)

**Comment by jorix** [comment]
If you do not explain my js code you wrote, I can not reproduce the problem.
Show me details of how you create the control, the template, how to run the filter ...
The popup follows the cursor only while it is over. Something fails you when you leave the ship. 
You see js errors on the console, which ones?
