### ISSUE TITLE
Changing z-index when adding layer

### ISSUE THREAD

**Issue by vdaoq** [jorix/OL-FeaturePopups#31]
I have several layers, some of them with pictures (left pic). 
When adding a layer with a line in FeaturePopups, it overlaps the other layers.
OpenLayers 2.13

``` javascript
//FeaturePopups without layerWithLine (left pic)
var fpControl = new OpenLayers.Control.FeaturePopups({
    layers: [
        [     
        layerOnTop, {templates: {           
            hover: "test"
        }}]
    ]
});
map.addControl(fpControl);

//When adding a layer with a line to FeaturePopups, it overlaps the other layers (right pic).
var fpControl = new OpenLayers.Control.FeaturePopups({
    layers: [
        [     
        layerOnTop, {templates: {           
            hover: "test"
        }}], [
        layerWithLine, {templates: {
            hover: "line"
        }}]
    ]
});
map.addControl(fpControl);
```

![fghjol](https://cloud.githubusercontent.com/assets/17796847/13722569/10925a00-e85b-11e5-8037-c93c97043256.png)

**Comment by jorix** [comment]
Yes, _FeaturePopups_ uses _SelectFeature_ and this control of _OpenLayers_ behaves this way. 

If you want to keep the order of the layers could add all layers and only define templates for which you are interested.

**Comment by vdaoq** [comment]
Thanks for answer!
I'll try to do it and reply.

**Comment by vdaoq** [comment]
It works. Thank you.

**Comment by jorix** [comment]
>It works. 

So I close it
