### ISSUE TITLE
Flicker popup at top-left position

### ISSUE THREAD

**Issue by vdaoq** [jorix/OL-FeaturePopups#32]
If popup position is /top-right/bottom-left/bottom-right/ all right. If position is top-left, then move mouse  popup flickers.
What could be the reason for such behavior?

This effect can be observed in example: 
http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.html
if you move mouse pointer from the bottom right  to the top left.

![test](https://cloud.githubusercontent.com/assets/17796847/13856047/747941a0-ec84-11e5-85e4-4c85a12adc14.png)

![git_1](https://cloud.githubusercontent.com/assets/17796847/13846049/637abae8-ec55-11e5-9dd4-c095c08b525d.png)

**Comment by jorix** [comment]
I assume that is using hover. 
The popup moves with the cursor to avoid flicker (if the cursor touches the popup starts flashing, if the popup does not move quickly also be problems), maybe the margin in px between cursor and popup is insufficient in this case. 
I should do tests. You can provide a piece of code to start tests?

**Comment by vdaoq** [comment]
Thank you for the prompt reply!
I've updated the question.
Yes, hover.
How can I define 'margin' or 'opacity' (I try hoverOptions, options, popupOptions, popupHoverOptions) for popup to avoid flicker ?

**Comment by jorix** [comment]
> How can I define 'margin' or 'opacity' ...

Not, when I have some time I look at it to remember and testing.

**Comment by jorix** [comment]
No need piece of code, now I see that you have used an example, better for testing.

**Comment by vdaoq** [comment]
What do you think about this (OpenLayers.Popup.Anchored):

```
           calculateNewPx:function(px) {
            var newPx = px.offset(this.anchor.offset);        
            var size = this.size || this.contentSize;

    var top = (this.relativePosition.charAt(0) == 't');
     var left = (this.relativePosition.charAt(1) == 'l');        

                   //add offset in "TL" case
                    if(top && left) {
                        newPx.x +=  -size.w - 10 ;
                        newPx.y += -size.h - 10;
                   } else {
                        newPx.x += (left) ? -size.w : this.anchor.size.w;
                        newPx.y += (top) ? -size.h : this.anchor.size.h;
                  }
            return newPx;   
        }`
```

**Comment by jorix** [comment]
@vdaoq  Please try a333591d1334c4372f5bf8f58a9734c3a90fb345

Thank!

**Comment by vdaoq** [comment]
Thank you! I'll try to do it and reply.

**Comment by jorix** [comment]
... without reply, I assume that now it works
