### ISSUE TITLE
question for OL-3

### ISSUE THREAD

**Issue by Bear4** [jorix/OL-FeaturePopups#33]
It's really big pity that there isn't such FeaturePopups for OL-3.
This is my best addition. 
Maybe there are any chanses ... ?
Anyway many thanks for OL-FeaturePopups.

**Comment by jorix** [comment]
Thanks, it is satisfying to know that it is still useful.

I do not have enough knowledge to undertake the task at OL3 :-(
(I did FeaturePopups after a couple of years to go deeply knowing the code of OL2)

**Comment by Bear4** [comment]
Very usefull. I have headake when I think about recode my OL-2 application to OL-3 ;)
It's brilliant idea to combined event popup: overlay and click.
God bless for Your work and effort.
