### ISSUE TITLE
GeoJSON support for Drupal

### ISSUE THREAD

**Issue by christianschoenmakers** [jorix/OL-FeaturePopups#34]
Hi, 

We have a problem with the OL-FeaturePopups module in Drupal 7. The popups are working great with a WFS layer, but when we enable it on a JSON layer, the features are placed randomly on the map. When we click them, the pop-up moves to the correct location of the feature. If we disable the functionality on the same layer, the feature show up on the correct position. 

Our setup uses Drupal with Cartaro distribution, OpenLayers 7.x-2.0-beta11 and OpenLayers Feature Popups 7.x-2.0-dev. Our map is in EPSG:28992 projection as well as the JSON data. 

Can you please help us with this problem?

**Comment by jorix** [comment]
@wespiremedia: Yes, I'll try to help.

I should be able to debug the code execution.
Is there a URL where I can run it?
When it fails there is some error js?

Another way would be you set up a minimal example without Drupal where it fails.
What version of OL2 do you use?
What OL2 modules require your example? Projections, styles ...?

**Comment by jorix** [comment]
... there's no response, closed
