### ISSUE TITLE
Remove duplicate names in cluster tooltips and popups

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#4]
I have features with the same name on a map (ends of road segments with incidents) and they appear as duplicates on tooltips and popups. Please give me an advice about how to remove duplicates and keep only features with unique names on tooltips and popups created with FeaturePopups control.

I asked for support for this problem here also:
http://gis.stackexchange.com/questions/41471/remove-duplicate-names-in-featurepopups-cluster-tooltips-and-popups

Thank you,
Bogdan

**Comment by jorix** [comment]
@bogdandragomir Control is quite customizable, but in this case we are in advanced customization ;-)

WARNING: To use this trick you should update the control, today it has made ​​a small adjustment.

---

It is necessary to rewrite the html list popup preparation as:

```
var fpControl = new OpenLayers.Control.FeaturePopups({        
    popupListOptions: {eventListeners: {
        "beforepopupdisplayed": function(e){
            var html = [],
                htmlAux = [];
            for (var i = 0, iLen = e.selection.length; i < iLen; i++) {
                var sel = e.selection[i],
                    layerObj = sel.layerObj;                
                for (var ii = 0, iiLen = sel.features.length; ii < iiLen; ii++) {
                    if (true) { // ******** FILTER DUPLUCATES HERE ******************
                        htmlAux.push(layerObj.renderTemplate(
                            layerObj.templates.item, sel.features[ii])
                        );
                    }
                }
            }
            html.push(layerObj.renderTemplate(
                layerObj.templates.list, {
                    layer: sel.layer,
                    count: sel.features.length,
                    html: htmlAux.join('\n')
                }
            ));
            e.html = html.join('\n');
        }
    }},
    ...
```

**Comment by bogdandragomir** [comment]
It works! Thank you Jorix!
But only on popups, what can I do to remove duplicates on tooltips also?

I will ask you another question, I don't know if here is the good place, please tell me if not.
I see that if you zoom after a popup is open it will not close when you click outside of it. Maybe it is a bug of OL you can work on as you on others.

I will place a link to these github pages on my questions from http://gis.stackexchange.com/.

Regards,
Bogdan

**Comment by bogdandragomir** [comment]
I see now that you already wrote on gis also. Thanks!

**Comment by bogdandragomir** [comment]
I tried to clone your code for popupHoverListOptions, but it is not working.
There are some differences in the attributes of objects. 
I am a newby on OL, please give me some advice.

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

I will not explain in detail (sorry), the code of "FeaturePopups" required more patches. Now we can be! (clean the cache)

See the new example:
  http://jorix.github.com/OL-FeaturePopups/examples/feature-popups-plus.html
there is also the alteracions to alter tooltips.

**Comment by bogdandragomir** [comment]
Hi Jorix!

It's nice how the cluster popup is closing when the new popup is open.
But I think there is a bug, there are too much bulets (li items twice
the number of features) on cluster popup.

Thank you,
Bogdan

Pe 22.11.2012 19:21, Xavier Mamano a scris:

**Comment by jorix** [comment]
@bogdandragomir 

> there are too much bulets (li items twice the number of features) on cluster popup.

This is an alteration in the html sought only to demonstrate how altering the html --thinking for duplicate filter case-- (though the popup is ugly)

**Comment by bogdandragomir** [comment]
I understand now :) Thank you, it's ok.

**Comment by jorix** [comment]
@bogdandragomir Thanks also to you, your feedback have caused be the control more versatile.
