### ISSUE TITLE
Click inheritance between cluster popup and child popup

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#5]
Hi Jorix, 

We found a bug on iPad with cluster popup. 

When you click a link on a cluster popup, the click is transferred to the child popup and if in the click area there is a link it is followed immediately.

I see this on Safari / iPad3 / iOS 6 on this page http://test2.trafficguide.ro/ when you click on a live camera cluster icon.

Please take a look!

Thank you,
Bogdan

**Comment by jorix** [comment]
@bogdandragomir 

I have not been able to test, but I think this can work, try b649332964eba80bb28adb4d91acf5fdc4ca4b46

Please confirm if it works, If not, we will try something stronger ;-)

**Comment by bogdandragomir** [comment]
Yes, it works, thank you!

Pe 25.11.2012 00:17, Xavier Mamano a scris:
