### ISSUE TITLE
Question: is it possible to use javascript code in popup?

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#6]
Hi Jorix!

I would like to show a live camera stream on popup and I have a Java Script code ready.
It should work with something like this, but it doesn't work:

> single: "&lt;script src='/gateway-live-camera.js.php?id=20' type='text/javascript'>&lt;/script>"

I tried but it is not working even with simple Java Script as:

> single: "&lt;script lang='javascript' type='text/javascript'>document.write('just a test!')&lt;/script>"

I made some tests with an html table outside of the script sequence to set some space, but nothing is generated inside this space.
The code is showed with no errors in Firebug, but nothing happens, it looks like it is not interpreted.

If document.write test will work I need to have a Java Script embedded and I have to situations: 
1. local JS file 
2. remote JS file. 

I am afraid remote JS file will not be permitted because of security reasons.
What do you think about this?

Thank you!
Bogdan

PS: 
I asked for help on GIS forum here http://gis.stackexchange.com/questions/41144/insert-javascript-code-in-popup-framedcloud. 
I think I can't try setContentHTML() with your library, but I will try iframes.

**Comment by jorix** [comment]
Hi @bogdandragomir ,

The first attempt can be made ​​with the event `"popupdisplayed"`.

See `popupListOptions: {...     eventListeners: {"popupdisplayed": display}}` in the example: http://jorix.github.com/OL-FeaturePopups/examples/strategy-cluster-FP.html 
you can use `event.popup.setContentHTML(...)` or.... `event.div.getXXXX()` 

Note: `...setContentHTML(...)` recalculate the size of the popup.

you can use `eventListeners` into the appropriate options depending on the type of popup: `"popupHoverOptions", "popupHoverListOptions", "popupSingleOptions", "popupListOptions"`, and `"popupListItemOptions"`

See http://jorix.github.com/OL-FeaturePopups/doc/FeaturePopups/all/files/lib/FeaturePopups-2-js.html#OpenLayers.Control.FeaturePopups.Popup.events, (oops!, now is updated)

**Comment by bogdandragomir** [comment]
Thank you Jorix, the Flickr example is fine!
I did not take it into consideration.

Pe 27.11.2012 18:01, Xavier Mamano a scris:
