### ISSUE TITLE
Change location.href on single click without opening popup.

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#9]
Hi Jorix, 

I need to open a new page on feature click, on a layer using clustering.
This code works fine for features on a cluster popup, but for single features it opens a popup before loading the new page:

```
single: function(feature) {
   location.href = "new-url.php?id=" + feature.attributes.id;
},
```

What should I do to not open the popup on single features click?
I tried with _return false;_ but nothing happens.
It works if I use _exit()_ after the _location.href..._ line, but because this generates a JS error :)

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

Try to use something like `singleEventListeners` on 67c48996c8d7fc033d9971b52e9e9dc1e607e624 it is managed by a popup object. 

(But `...  single: function(feature) { ...` is managed by a layer object and this delegates the work of display to any popup object.)

**Comment by bogdandragomir** [comment]
Thank you Jorix!

I tried this way:

```
var singleEventListeners = {
    "beforepopupdisplayed": function(e) {
        var sel = e.selection;
        if (sel.layer === layerRadare)
            location.href = "camere-radare-rovigneta.php?tip=radare&id=" + sel.feature.id;
        else if (sel.layer === layerCamereRovigneta)
            location.href = "camere-radare-rovigneta.php?tip=camere-rovigneta&id=" + sel.feature.id;
        else if (sel.layer === layerCamereLive)
            location.href = "camere-radare-rovigneta.php?tip=camere-live&id=" + sel.feature.id;
        return false;
    }
};

var fpControl = new OpenLayers.Control.FeaturePopups({
    boxSelectionOptions: {},
    selectOptions: {clickout: true},
    mode: OpenLayers.Control.FeaturePopups.DEFAULT & 
          ~OpenLayers.Control.FeaturePopups.CLOSE_BOX,

    popupSingleOptions: {
        eventListeners: singleEventListeners
    },
    popupListItemOptions: {
        eventListeners: singleEventListeners
    },
```

but singleEventListeners initialisation is not interpreted. 
I use a break point in Firebug on this line and nothing happen:
if (sel.layer === layerRadare)

Do you know what could it be?

**Comment by jorix** [comment]
I see nothing wrong, could you put somewhere where I can debug it?

The only thing that should be adjusted is the `return false;` if there are other layers with a single popup. But that would be later when the function was called correctly.

**Comment by bogdandragomir** [comment]
I have updated the code here http://test2.trafficguide.ro/ to show an alert with the feature ID on live camera layer.
It works but just for clusters. It should work for single popup also.

I set a breakpoint on line "var sel = e.selection;" and it stops here for both types of popups: single and cluster, but the alert window appear just for clusters.

I can't give you access to the CMS where it doesn't work at all, but I hope if you have an explanation for this behaviour in public area I can find myself a solution.

Thank you!

**Comment by bogdandragomir** [comment]
I think I found. It is necessary to have this line, even it is not shown:
`single: '${.name}',`

Now it works in the CMS.

**Comment by jorix** [comment]
you have gone faster than me, yes, if no template behavior disappears. (I think even `single: '',` would work)

**Comment by bogdandragomir** [comment]
No, `single: ''` is not working. Anyway thank you for support :)

**Comment by jorix** [comment]
true, requires at least one space.

**Comment by bogdandragomir** [comment]
I still have the popup visible on single features on the CMS with the code updated as above.
And this popup looks like cluster popups with title and link on the single feature name.
But if I comment those lines I see a single popup without title and link:

```
popupSingleOptions: {eventListeners: singleEventListeners},
popupListItemOptions: {eventListeners: singleEventListeners},
```

Can you suggest me something?

**Comment by jorix** [comment]
> And this popup looks like cluster popups with title and link on the single feature name.

What you mention seems that the 'single' template is not defined, then if there is a cluster with one feature displays a list with one element.

But in this case I must meditate (it is not desired behavior) since the 'single' template exists.  ... ...

**Comment by bogdandragomir** [comment]
Yes, it exists. See this screen shot:

![snap182](https://f.cloud.github.com/assets/2846921/34821/2807931a-5148-11e2-80f4-86c12ab8743d.jpg)

Please let me know if you find some possible reason for this.
And I will try to create a demo so you can view and debug it.

Thanks!

**Comment by jorix** [comment]
> Please let me know if you find some possible reason for this.

Yes it is a bug, I'm working on it.

Sorry, above I will not detail explained, before I saw that something is wrong.

**Comment by bogdandragomir** [comment]
I reproduce this behaviour in the public area of the test server (http://test2.trafficguide.ro/).

If I remove this code the popup appears (as cluster even for single features) for short time and then the browser loads the new page.

```
    // ** Overwrites html of the list popups **
    popupListOptions: {eventListeners: {
        "beforepopupdisplayed": function(e){
            var html = [],
                htmlAux = [],
                feature0 = null,            // salvam aici primul feature, iar daca e unic il afisam direct in popup-ul cluster, nu ca link.
                namesInPopup = [];
            for (var i = 0, iLen = e.selection.length; i < iLen; i++) {
                var sel = e.selection[i],
                    layerObj = sel.layerObj;                
                for (var ii = 0, iiLen = sel.features.length; ii < iiLen; ii++) {
                    feature0 = sel.features[ii];
                    if (jQuery.inArray(feature0.attributes["name"], namesInPopup) == -1) { // ******** FILTER DUPLICATES HERE ******************
                        htmlAux.push(
                            layerObj.applyTemplate.item(feature0)
                        );
                        namesInPopup.push(feature0.attributes["name"]);
                    }
                }
            }
            if (htmlAux.length === 1) {
                layerObj.control.popupObjs.single.showPopup({
                        layerObj: layerObj,
                        layer: layerObj.layer,
                        feature: feature0
                    }, 
                    feature0.geometry.getBounds().getCenterLonLat(), 
                    layerObj.getSingleHtml(feature0).html, 
                    true
                );
                return false;
            }
            html.push(layerObj.renderTemplate(
                layerObj.templates.list, {
                    layer: sel.layer,
                    count: sel.features.length,
                    html: htmlAux.join('\n')
                }
            ));
            e.html = html.join('\n');
        }
    }},
```

This is the code which eliminates duplicates from the cluster popup.
I don't understand what is the relation with our _singleEventListeners()_ but I am sure you understand.

**Comment by jorix** [comment]
@bogdandragomir 

Try this patch d7214b14639691f7ef310dbaa3dc98148b8f9854

**Comment by bogdandragomir** [comment]
It works OK. Thank you!
